name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: Branch Name
        required: true
        


jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo $GITHUB_REPOSITORY
        echo "https://github.com/${{GITHUB_REPOSITORY}}/actions"
        echo "Hello ${{ github.event.inputs.name }}!"
        
