name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: Branch Name
        required: true
        
env:
  AZURE_WEBAPP_NAME: githubactiondemo  # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }} # set this to the path to your web app project
  JAVA_VERSION: '1.8'                # set this to the node version to use
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_PUBLISH_PROFILE }}     # set GH repo secret with the publish profile of the web app
  GITHUB_REPOSITORY : ${{github.repository}}

jobs:
  build-and-deploy-prod:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@github.event.inputs.name
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.war'
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: <html><body>Deployment to Production Successful</body></html>
        # Read file contents as body:
        to: mayurcapg@gmail.com
        from: Mayur Shinde # <user@example.com>
        # Optional content type (defaults to text/plain):
        content_type: text/html
        
