# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ mayurjs26-rollback ]
  pull_request:
    branches: [ mayurjs26-rollback ]

env:
  GITHUB_REPOSITORY : ${{github.repository}}
  GITHUB_WORKSPACE : ${{ github.workspace }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build with Maven
      run: mvn package --file pom.xml
    - uses : actions/upload-artifact@master
      with :
        name : DemoProject.war
        path: ${{env.GITHUB_WORKSPACE}}/target/*.war
