
# This is a basic workflow to help you get started with Actions

name: RollBack

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
      workflow_dispatch:
        inputs:
          name:
            description: Please Enter Branch Name
            required: true

env:
  GITHUB_REPOSITORY : ${{github.repository}}
  GITHUB_WORKSPACE : ${{ github.workspace }}

jobs:
  upload-artifact:
    name: RollBack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build with Maven
      run: mvn package --file pom.xml
    - uses : actions/upload-artifact@master
      with :
        name : DemoProject.war
        path: ${{env.GITHUB_WORKSPACE}}/target/*.war
    - uses: actions/download-artifact@v2
      with:
        name: DemoProject.war
    - name: Display structure of downloaded files
      run: ls -R
